### ISSUE TITLE
Linux wallet?

### ISSUE THREAD

**Issue by lubuzzo** [chaincoin-legacy/chaincoin#10]
Please make a release of wallet for Linux. <3

If you need some help to do that, let me know.

**Comment by brakmic** [comment]
I've just successfully compiled a wallet under ubuntu linux. 

![ubuntu_wallet](https://preview.ibb.co/f2Qmh5/wsl_ubuntu.png)

There was an issue with Berkeley-DB which stopped the compilation but I was able to find a remedy. Basically you have to rename a certain function from *atomic.h* header that collides with some internal functions of clang. The updated docs are currently on my own fork but soon they'll be merged into the main tree, I think. For the time being I'd recommend you to look at the updated doc on my page and compile the wallet. If there are any problems, please, feel free to write them here. 

https://github.com/brakmic/chaincoin/blob/master/doc/build-unix.md

Regards,

**Comment by PW00X** [comment]
@brakmic I'm having trouble compiling on Debian 9
https://pastebin.com/JBuNJcFW

**Comment by brakmic** [comment]
This is a problem with openssl includes not with chaincoin.

**Comment by PW00X** [comment]
My bad, Solved after installing libssl1.0-dev in addition to libssl-dev
Now I have a different problem due to using a newer boostlib I guess, looking or a solution my self atm might become a pull request.
https://pastebin.com/UYNxP3Dy

**Comment by brakmic** [comment]
ok. may I ask you to cut all these long logs?

**Comment by PW00X** [comment]
Still wasn't able to compile, I think it's similar to https://github.com/litecoin-project/litecoin/pull/241/commits/b513bc41337c9c983acdc199ce9b42382c23b658
