### ISSUE TITLE
chaincoind: command not found

### ISSUE THREAD

**Issue by marcorangel** [chaincoin-legacy/chaincoin#110]
I'm doing the step-by-step installation of the masternodo on ubuntu, when I'm on the command of chaincoind --daemon, it shows me the error "chaincoind: command not found"

What I can be doing wrong?

**Comment by suprnurd** [comment]
see point 20 here **https://github.com/chaincoin-legacy/chaincoin/wiki/Frequently-Asked-Questions-(FAQ)**

**Comment by marcorangel** [comment]
I worked using this repository:
https://github.com/chaincoin-legacy/chaincoin.git
