### ISSUE TITLE
problems on payout on Masternodes 

### ISSUE THREAD

**Issue by JGTX** [chaincoin-legacy/chaincoin#13]
What is going on with Masternode payout the page calculater its wrong and also payouts are no consistent some days get 2 coin other day we don't can you please explain the Masternode payout ? I have 5 Masternode running and in the las days some get payouts other do not. this need to be fix . please provide a solution to this problem.

**Comment by major684** [comment]
maternode payout is on a lottery system, the masternode payout site just shows a daily average sometimes you can get paid many times a day and then go a couple days before your next payment, future payments will be moving from a lottery system to a set payout system where nodes get paid in order
