### ISSUE TITLE
Log rotate

### ISSUE THREAD

**Issue by Antoun98** [chaincoin-legacy/chaincoin#14]
Debug.log file needs to be rotated after a set size. Example debug.log, debug1.log, debug2.log. after third rotate overwrite first log.

This is to ensure the size does not get extreme.

**Comment by brakmic** [comment]
I saw the commit for a new logging engine was reverted. Don't know why but if there's no other currently working on it I'd like to check out if we could maybe use some of the more standard and proven methods like those from the Apache project. Their licenses are also very liberal and should not clash with our own, if I'm not mistaken.
