### ISSUE TITLE
Masternode: multi-port / single IP / single wallet / multiple wallet addresses

### ISSUE THREAD

**Issue by cryptorex** [chaincoin-legacy/chaincoin#18]
**Background**

Based on the bitcoin / dash core implementation it appears that we could bind a chaincoin masternode to multiple ports on the same IP being controlled by the same wallet holding multiple addresses.

**Evidence**

Aside from interpreting the bitcoin and dash core, it seems that running ```chaincoind masternode list | more``` results in a lengthy list of duplicate IPs bound to multiple ports, some showing in excess of 10.

**Potential moot issue - Point#1**

Masternode operators could run multiple instances of chaincoind (daemon) mapped to different directories as a possible solution, but did not test due to space constraints on free tier AWS. Although the blockchain isn't large, this solution is not forward looking for the future of this coin and also leads to other overhead and deployment constraints. 

**Potential moot issue - Point#2**

Daemon is not designed to bind to multiple ports on same ip, etc.

**Potential moot issue - Point#3**

I don't know what I'm doing.

**Testing Environment Assumes**

Ubuntu 16.04 x64
Kernel 4.4.0-1013-aws
Security Groups edited for open port designation
Single IP
Single wallet.dat
Multiple wallet addresses in one wallet.dat with 1000 CHC each

**Main Testing - Scenario**

1. The chaincoin.conf file contains standard arguments

    rpcuser=random_user
    rpcpassword=random_password
    server=1
    listen=1
    daemon=1
    masternode=1
    masternodeprivkey=privkey1
    masternodeaddr=<IP_ADDRESS>:11995
    masternode=2
    masternodeprivkey=privkey2
    masternodeaddr=<IP_ADDRESS>:11996

2. The masternode.conf contains 

    NODE1 IP:11995 NODE PRIVKEY1 TXID_FOR_1000_CHC INDEX_FOR_TX
    NODE2 IP:11996 NODE PRIVKEY2 TXID_FOR_1000_CHC INDEX_FOR_TX

3. After starting daemon, running ```chaincoind masternode start-many WALLET_PW``` results in the following error:

```bash
{
    "overall" : "Successfully started 0 masternodes, failed to start 2, total 2",
    "detail" : {
        "status" : {
            "alias" : "NODE1",
            "result" : "could not locate vin"
        },
        "status" : {
            "alias" : "NODE2",
            "result" : "could not locate vin"
        }
    }
}
```

4. Above issue solved by entering:

```bash 
chaincoind lockunspent true "[{\"txid\":\"TXID_FOR_1000_CHC\",\"vout\":0}]"
chaincoind lockunspent true "[{\"txid\":\"TXID_FOR_1000_CHC\",\"vout\":1}]"
```

5.  With daemon running, executing ```chaincoind masternode start-many WALLET_PW``` results in successful load:

```bash
{
    "overall" : "Successfully started 2 masternodes, failed to start 0, total 2",
    "detail" : {
        "status" : {
            "alias" : "NODE1",
            "result" : "successful"
        },
        "status" : {
            "alias" : "NODE2",
            "result" : "successful"
        }
    }
}
```

6.  Telnet to localhost on designated ports 11995 and 11996 does not result in a connection.

7.   Executing ```netstat``` does not show the designated ports open.

8.   Executing ```chaincoind masternode stop-many``` results in a "Darksend" error:

```bash
{
    "overall" : "Successfully stopped 0 masternodes, failed to stop 2, total 2",
    "detail" : {
        "status" : {
            "alias" : "NODE1",
            "result" : "failed",
            "errorMessage" : "Darksend Masternode List doesn't include our Masternode, Shutting down Masternode pinging service! CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase )"
        },
        "status" : {
            "alias" : "NODE2",
            "result" : "failed",
            "errorMessage" : "Darksend Masternode List doesn't include our Masternode, Shutting down Masternode pinging service! CTxIn(COutPoint(0000000000000000000000000000000000000000000000000000000000000000, 4294967295), coinbase )"
        }
    }
}
```

**Alternative Testing - Based On Scenario Above**

1.   Adjusted chaincoind.conf to only include rpc arguments and no masternode arguments, relying solely on masternode.conf

2.   Adjusted chaincoind.conf to only include rpc arguments and server=2 and no masternode arguments, relying solely on masternode.conf

3.  Adjusted chaincoind.conf to only include rpc arguments and masternode=0 arguments, relying solely on masternode.conf

**Conclusion**

- Continued testing could be undertaken to achieve intended results based on guidance. 
- Implement multiple port binding to single IP where single wallet is used containing multiple wallet addresses.

**Comment by brakmic** [comment]
If I'm not mistaken *masternode=1* represents a **binary value** (0 or 1). Using *masternode=2*, *3* etc. would break backwards compatibility. I think we need another parameter here, maybe something like **multimasternode=1**

**Comment by cryptorex** [comment]
Yes - definitely seems to work that way.  During my research I compiled several scenarios gathered from multiple sources and one of them was to ignore that masternode=1 represents binary value, hence the masternode=2.

Further testing involved removing masternode directives form the chaincoin.conf file entirely and relying on masternode.conf.

Agreed, something like **multimasternode=1** or **masternodeports=11994,11995,11996** or **mnports=11994,11995,11996**.

**Comment by joaoluizcadore** [comment]
Hi there, I'm running multiple nodes in the same server. I just want share how I'm doing that.
Inside my .chaincoin folder:
```
xxxx@masternode:~/.chaincoin$ ls
masternode01  masternode02  mn01.conf  mn02.conf
```
 masternode01  and masternode02 -> Folders with the entire blockchain/wallet/etc..
mn01.conf and mn02.conf -> Configuration files

```
$ cat mn01.conf
rpcuser=xxxx
rpcpassword=xxxxx
rpcallowip=127.0.0.1
rpcport=9880
daemon=1
server=1
listen=1
maxconnections=256
masternode=1
externalip=my_ip_address
bind=my_ip_address
port=11994
masternodeaddr=my_ip_address:11994
masternodeprivkey=XXXXX
datadir=/home/XXXX/.chaincoin/masternode01/
pid=/home/XXXX/.chaincoin/masternode01/chc_pid.pid
```

```
$ cat mn02.conf
rpcuser=xxxx
rpcpassword=xxxxx
rpcallowip=127.0.0.1
rpcport=9881
daemon=1
server=1
listen=1
maxconnections=256
masternode=1
externalip=my_ip_address
bind=my_ip_address
port=11995
masternodeaddr=my_ip_address:11995
masternodeprivkey=XXXXX
datadir=/home/XXXX/.chaincoin/masternode02/
pid=/home/XXXX/.chaincoin/masternode02/chc_pid.pid
```

----
Running RCP commands:
```
$ chaincoind --conf=mn01.conf getinfo
$ chaincoind --conf=mn02.conf getinfo
```

It is working very well. But I think soon it won't work any more. There is an update that will require only  the port 11994. So, one masternode per IP:11994. Still don't know why.

**Comment by brakmic** [comment]
@joaoluizcadore since version 0.9.30 only a single MN per IP:PORT is allowed. The fact that one could run multiple MNs behind a single IP never was officially supported and also not always possible on all platforms. For example, it was really problematic to run similar configurations under Windows. Your perception of this "feature" is based on Linux.

**Comment by joaoluizcadore** [comment]
@brakmic Thanks, soon I will update my masternodes and run a single instance each server. Yes, it is based on linux.
Cheers.

**Comment by IgorVeyn** [comment]
All greetings, installed Masternode for Mac Hosting, but it does not make a profit, in the account as it was 1000 (CHC), and it remains, who faced?

**Comment by brakmic** [comment]
@IgorVeyn 

This is GitHub, a place where we discuss *Software Development* of Chaincoin. 

**Support questions** belong to our [slack channel](https://chaincointeam.slack.com/messages). We have a channel dedicated to support questions regarding masternodes: *#masternodes*.
