### ISSUE TITLE
Masternode Payouts

### ISSUE THREAD

**Issue by chaoabunga** [chaincoin-legacy/chaincoin#24]
Hi, I have been running CHC masternodes for awhile now and the payments have always came at an expected time frame.  But recently I've noticed it going out of the expected time frame.  Currently according to chc.masternodes.pro the payout should be around 0.70 CHC per day...with MN reward at 2CHC, the average time frame to get paid should be around 2 / 0.70 ~ 3 Days.  

Also given the fact Chaincoin has seen a huge rise in Masternode count in the last week.  I would give the benefit of the doubt to the network.  But if masternodes are not seeing payments in about a week, i'd think it would make a lot of people worried.

Any technical reasons why is it doing this?  And what can I tell my viewers for my technical support on how to to wait to expect masternode payments? 

Thank you very much,
Chao
My live masternode tech support channel
https://www.youtube.com/channel/UCdIQkbmfMNtqQgqvF9NNWyA/live

**Comment by brakmic** [comment]
This is not a development-related question. Please do not misuse GitHub for support- and/or usage-Questions. GitHub is where we develop software.

These things should go to our #masternode slack and/or discord channels.

Thanks.

**Comment by chaoabunga** [comment]
Ok, I understand, thank you.
