### ISSUE TITLE
Bootstrap File

### ISSUE THREAD

**Issue by major684** [chaincoin-legacy/chaincoin#3]
Please add bootstrap file to speed up blockchain sync.

**Comment by suprnurd** [comment]
url: https://toaster.chaincoin.org/bootstrap/1364170/bootstrap.dat
md5: 1551af74548e052d2c6297d53395c4fb

url: https://toaster.chaincoin.org/bootstrap/1364170/md5
md5: 0c7e11fc5bad4b1be4cf210befcbe0ba

**Comment by suprnurd** [comment]
I had another user confirm the bootstrap is working correctly. I will put together a guide on how to use it as well as make the links more prominent on the release/download page and wiki.
