### ISSUE TITLE
Cannot compile with ubuntu 16.04

### ISSUE THREAD

**Issue by yajiedesign** [chaincoin-legacy/chaincoin#39]
in ubuntu  16.04. it not libssl 1.0, it not compile .

**Comment by suprnurd** [comment]
I used the following from a clean install to get the necessary dependencies and compile successfully on Ubuntu 16.04:

sudo apt-get install automake libdb++-dev build-essential libtool autotools-dev autoconf pkg-config libssl-dev libboost-all-dev libminiupnpc-dev git software-properties-common python-software-properties g++ bsdmainutils

sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev

**Comment by yajiedesign** [comment]
thanks.I succeeded go back to the 1.0.2 .it work.
do you have a plan compatible with 1.1.0?
