### ISSUE TITLE
Wallet - UI bug // tiny UI on 4K Display Resolution 

### ISSUE THREAD

**Issue by donkhu** [chaincoin-legacy/chaincoin#44]
The UI Elements are barely readable on my 4K Display (Dell XPS 15) as well as my 4K LG Display.
Everything is very small (Icons, Fonts)

**Comment by chaincoin-legacy** [comment]
Try your operating system's scaling features.

**Comment by donkhu** [comment]
if i use the scaling option of windows 10 Its only a hacky solution, because all other programs i use will then become gigantic (icons and text). The wallet is not suitable for high dpi displays at this moment obviously. But there are a lot of displays like mine in the wild. It would be great if you would look into it. 
![bug](https://user-images.githubusercontent.com/30731969/29495805-b0a87e34-85c6-11e7-9dbc-ddef64e6adbe.jpg)
