### ISSUE TITLE
Masternode/Daemon stop

### ISSUE THREAD

**Issue by chaincoin-legacy** [chaincoin-legacy/chaincoin#52]
- Sometimes when a running masternode is stopped with the "masternode stop" rpc call, the call never returns.
- Thereafter when the node is stopped with the "stop" rpc call, the call returns, but the process never dies and has to be killed manually.

**Comment by brakmic** [comment]
The PR #59 targets this issue. Here's a comparison of debug-logs from the current version and the proposed one:

**Current**

![Current](https://img1.picload.org/image/rwoagpgl/old.png)

**Proposed**

![New](https://img1.picload.org/image/rwoagpga/new.png)

**Comment by suprnurd** [comment]
This was fixed indeed.
