### ISSUE TITLE
log rotator problem during MN sync process

### ISSUE THREAD

**Issue by reindersgh** [chaincoin-legacy/chaincoin#55]
Wallet version 90300 of my masternode is filling up the VPS disk space with log files in the .chaincoin directory during the time the blockchain is syncing.
Instead of creating one debug.log file, it's creating a new file every minute with names like: 

- debug-2017-08-09 21:16:25.log
- debug-2017-08-09 21:17:08.log
- etc.

I'm running the 90300 wallet version on Ubuntu 14.04.5

At this moment all these files are about 12 megabytes in size and filling up the VPS disk space. 

On my other MN, which is running the wallet version 90205 and CentOS 7, this did not happen during the MN setup, here it only created 1 debug.log file when I set it up about 1 month ago.

**Comment by brakmic** [comment]
The latest version 0.9.3.0 introduced a log-rotator that creates a new log-file after having reached the 10MB limit. This way we prevent creation of a single large log-file. If you don't want to keep the old logfiles around I'd recommend you to create a simple cronjob that removes the old logfiles.

Here's a simple example of a **cronjob** that on **each day at 10:00 AM** deletes all *debug-* files. The only debug file that will remain is the current one (without "-" in its name).

Type in *crontab -e* to open a file where all of your cronjobs are. Then add this line below:

```shell
0 10 * * * find $HOME/.chaincoin -name "debug-*.log" -exec rm {} \;
```

**Comment by brakmic** [comment]
This [patch](https://github.com/chaincoin/chaincoin/pull/60) should fix the problem for all OS as the above workaround only helps Linux/Mac users. Windows doesn't have an easy, one-line solution that's similar to *cronjobs*.
