### ISSUE TITLE
Open Configuration File doesn't work in new wallet

### ISSUE THREAD

**Issue by raympie1977** [chaincoin-legacy/chaincoin#63]
Hi, I am trying to create the MAsternode from my CHC Wallet, but clicking on Open Configuration File doesn't open it...

**Comment by brakmic** [comment]
Before writing here, please, visit our slack masternode channels. You can't simply come here and write that "something doesn't work". We need error messages and other, more informative data.

**Comment by raympie1977** [comment]
I have done that. Nothing helped. There is no message, as it just does not open the configuration file when you click on the menu item: open configuration file. However, you can click Open Debug Console and it will open or Show Automatic Backups, opens also. And I was redirected to here from the Slack channel, sir.

**Comment by brakmic** [comment]
Ok, all good. But now you have experienced the difference between forums, chats...and github. 
*So, we will see what we can do.* As you are the only one reporting this problem we can't simply generalize it. Too risky to change anything.

Regards,

**Comment by joaoluizcadore** [comment]
@raympie1977 I did some tests here. What I found is when doesn't exist the file chaincoin.conf into the chaincoin folder and then we click on Tools / Open Configuration File it wont open anything.
One easy way to fix it is:
Open the Terminal app and type: 
`
touch ~/.chaincoin/chaincoin.conf
`
Then it will work. Remember, chaincoin.conf is the configuration related the wallet and masternode locally. If you want control masternode remotely, you need to have a file called masternode.conf. 
Where you will add all your masternodes.  
You can follow this guide:  https://toaster.chaincoin.org/docs/convert_masternode_to_controller.pdf

The masternode.conf file has to be created inside the folder ~/.chaincoin as well.

**Comment by suprnurd** [comment]
If I'm not mistake, the wallet should create an empty chaincoin.conf file when it starts up for the first time.

**Comment by howardfinter** [comment]
@suprnurd you are correct. The wallet is working properly. Tools>Open Configuration File is working and allows for editing.

**Comment by alec-djinn** [comment]
It does the same on MacOS. The configuration file is in `Library/Application Support/Chaincoin` but when I click `Tools>Open Configuration File` it does nothing.
