### ISSUE TITLE
MasternodeList::updateMyMasternodeInfo parameter not checked

### ISSUE THREAD

**Issue by yajiedesign** [chaincoin-legacy/chaincoin#69]
the parameter  `infoMn ` is not check.when mn not run.it is null.it will be crash.

**Comment by brakmic** [comment]
Please be more precise. Your issue is also not very readable. Do not expect others to guess your thoughts.

Thanks!

**Comment by chaincoin-legacy** [comment]
It looks like it is only called when there is a masternode config:

masternodelist.cpp line 239:

    BOOST_FOREACH(CMasternodeConfig::CMasternodeEntry mne, masternodeConfig.getEntries()) {
...
        updateMyMasternodeInfo(QString::fromStdString(mne.getAlias()), QString::fromStdString(mne.getIp()), infoMn);
}

**Comment by yajiedesign** [comment]
https://github.com/chaincoin/chaincoin/blob/master/src/qt/masternodelist.cpp#L186
`infoMn` some time is null.please check it.

**Comment by yajiedesign** [comment]
https://github.com/chaincoin/chaincoin/blob/master/src/qt/masternodelist.cpp#L247
this line ` CMasternode *infoMn = mnodeman.Find(txin);` not always find some item.

**Comment by brakmic** [comment]
Could this be related to the sudden core dump we experienced after my [pull request](https://github.com/chaincoin/chaincoin/pull/68). I am only speculating here as I'm not into QT.

**Comment by yajiedesign** [comment]
it cause core dump.

**Comment by brakmic** [comment]
@yajiedesign yeah, it core dumped but your core dump could be another one. I am still speculating here. :)

**Comment by brakmic** [comment]
And btw. I use a masternode.conf.

**Comment by chaincoin-legacy** [comment]
A fix for this will follow.

**Comment by chaincoin-legacy** [comment]
Included in this commit

https://github.com/chaincoin/chaincoin/commit/7b8ae63c5c5e9fe73b4edb9dd1944fcfcf721f57

**Comment by brakmic** [comment]
I'd like to thank you @yajiedesign for helping us find this bug. 👍 ❤️

**Comment by yajiedesign** [comment]
ok.thanks
