### ISSUE TITLE
New masternodes and wallets not synchronising

### ISSUE THREAD

**Issue by viklas** [chaincoin-legacy/chaincoin#7]
**This issue may only be relevant today (16/7/2017) as it seems to be load related. If the issue goes away, please feel free to close this issue.**

**Background:** A number of users on Chaincoin and HighOnCoins slack channels have been struggling to get their new masternodes working. Despite following the instructions exactly. 

**Symptom:** After starting chaincoind for the first time (in Ubuntu 14.04 VM hosted in Vultr), the daemon starts, but there are multiple errors in the debug log. Mainly "Connection refused" to two IP addresses (213.32.15.35:11994 and  51.15.60.194:11994)

**Attempted fixes:** Lots of people trying fixes (for masternode scenarios) like deleting peers.dat file and restarting the daemon. Some reports this works, but I haven't seen that in my testing.

**Theory:** All the new masternodes and wallets are effectively performing a denial of service attack on chaincoin infrastructure, somehow.

**Analysis:** Checked out the chaincoin code, and searched through for any references to seednodes. Found entries in \src\chainparams.cpp pointing to 4 chaincoin DNS addresses (seed1.chaincoin.org, seed2...etc). Pinged those addresses and found that they resolved to the IP addresses above.

<img width="910" alt="screenshot 2017-07-16 23 20 08" src="https://user-images.githubusercontent.com/7428988/28248149-f10e334c-6a82-11e7-8a85-ef487edd20b7.png">

**Workaround test:** Changed host file on (broken) masternode to point to a 'known good' masternode (I had one that I setup the day before that came online before the load issue emerged). After restarting daemon, the debug log immediately started showing 'success' messages.

**Confirmation:** On slack channel, got confirmation from two other users that the same 'hosts file hack' worked for them too. Not 100% confirmed, but looks promising.

Please look into this ASAP chaincoin devs. It is impacting a lot of people who want to support the HODL movement. I'm guessing just adding more seed nodes would work, or scaling up/out the number of hosts. Happy to make a donation if you need funding (I'm sure others would too)

**NOTE: I am NOT recommending that hundreds of people hard code DNS entries, and somehow start breaking other, working masternodes. But this seems to be a temporary workaround whilst you guys work on the larger issue.**

#PowerToThePeople

**Comment by viklas** [comment]
**Update:**

@destrega (on slack) suggested a better approach as a workaround. A list of hosts to be added to the chaincoin.conf file.

**Second Update:** Some folks are looking at how to produce a script to spread the load across more nodes, so that that @Destrega fix doesn't hammer those nodes listed below.

**Comment by Destrega** [comment]
**Please don't make any hacks in the code**, just add some other nodes so you can sync naturally.

**Step 1:** Shut down your wallet/node.

**Step 2:** Open your chaincoin.conf file, it should be located in the same folder as your wallet.dat file. If it doesnt exist, create one.

**Step 3:** Add some nodes in your chaincoin.conf file under listen=1 and save it:

addnode=1.2.3.4 
addnode=1.2.3.4
addnode=1.2.3.4

Replace the 1.2.3.4 with the IP adress of a node. You can find IP's here: http://104.238.153.140:3001/network 3-10 addnodes should be enough.

**Step 4:** Start your wallet/node again

Syncing from scratch can take a few hours, so please be patient.

**Edit**
I removed the node IP's because some were getting to much traffic, please select some random IP's near your location on http://104.238.153.140:3001/network yourself so we distribute the load.

**Comment by PowellT** [comment]
Thanks @Destrega that worked like a charm

**Comment by ghost** [comment]
Destrega How many chc r u getting per day .. with the fix?

**Comment by Destrega** [comment]
Currently i'm getting about 2 per node per day. It took 2 days before the first payment so a little patience is required ;)

**Comment by ghost** [comment]
Awesome .. am also getting 2 per day so maybe this is a window only problem?

**Comment by ghost** [comment]
Wait .. he said its a vultr ubuntu vm .. hmm.

**Comment by viklas** [comment]
I just got my first 2 after about 36 hours...running an impatient little loop against my node to keep checking my balance. Here it is...

$ while :; do clear; ssh -i ~/.ssh/{yourPrivateKeyfile} {yourID}@{yourMNodeIP} chaincoind getinfo | grep -i "balance" | grep -i -v "darksend"; sleep 30; done

**Comment by ghost** [comment]
@viklas Lol

**Comment by Destrega** [comment]
The OS you are running on does not matter. You can check your balance anywhere by checking:
104.238.153.140:3001/address/youriphere

**Comment by ghost** [comment]
@Destrega it crashed ...

**Comment by viklas** [comment]
@kelonye - might be better for troubleshooting to head over to the slack group for chaincoin, just to avoid flooding this Github issue. Makes it a bit harder for the devs to do their work if we chat too much in here. Just a suggestion.

**Comment by viklas** [comment]
_Just putting this here for the scrollers:_

**Second Update**: Some folks are looking at how to produce a script to spread the load across more nodes, so that that @Destrega fix doesn't hammer those nodes listed above.

**PLEASE get a fresh list of IP addresses followin @Destrega instructions - don't use the one's listed above**

**Comment by Destrega** [comment]
I edited my post

**Comment by chaincoin-legacy** [comment]
Number of seed nodes increased in release 0.9.2.5
Also plan to setup a dns seeder to give fresher addresses.
