### ISSUE TITLE
cURL

### ISSUE THREAD

**Issue by mikeydiamonds** [chaincoin-legacy/chaincoin#81]
Maybe not the best placed to ask this but I'm at a loss. I'm trying to use curl to return json data from a chaincoin node. This is my code:

` curl -u username:password --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "listaccounts", "params": [6] }' -H 'content-type: text/plain;' http://127.0.0.1:11994/`

Got this from [Bitcoin API Docs](https://chainquery.com/bitcoin-api/listaccounts). Any direction on why I get `curl: (52) Empty reply from server`

**Comment by joaoluizcadore** [comment]
You should call the right RPC service, stead of call the masternode service.
Have a look at your chaincoin.conf file, look at the config:
`rpcport=XXX`

That's the right port to make rpc calls.

**Comment by mikeydiamonds** [comment]
Thanks for the info @joaoluizcadore. I didn't even have a rpcport listed in .conf file. I used port 8333. It's now working. On to verifying messages :)
