### ISSUE TITLE
Miners stealing rewards from masternodes

### ISSUE THREAD

**Issue by cryptoninjapanda** [chaincoin-legacy/chaincoin#85]
I just got 2 CHC reward instead of 2.8 reward on one of my nodes it seams that some people are abusing the system to get old rewards. Is it possible to enforce protocol 70003 so we can stop the thieves.

**Comment by suprnurd** [comment]
Yes once the community has the ability to release a stable update we are
planning to cut off the older protocol.

We did have many pools update their wallets I wonder where the hashing
power came from...

**Comment by suprnurd** [comment]
Looks like the big man himself has dropped by to save us all from abuse!
