### ISSUE TITLE
error while loading shared libraries: libdb_cxx-4.8.so

### ISSUE THREAD

**Issue by AndyBrooks** [chaincoin-legacy/chaincoin#89]
I get this message after trying to start chaincoind --daemon
error while loading shared libraries: libdb_cxx-4.8.so

I can correct the issue with this command
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/BerkeleyDB.4.8/lib"

Then I can start the daemon. The need for the export makes it so I can't autostart the daemon on reboot.

What can I do to make this export automatic or permanent?

**Comment by suprnurd** [comment]
@AndyBrooks why don't you just make yourself a little launch script then?

#!/bin/bash
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/BerkeleyDB.4.8/lib"
/usr/local/bin/chaincoind -daemon
