### ISSUE TITLE
build errors in 0.12.X

### ISSUE THREAD

**Issue by suprnurd** [chaincoin-legacy/chaincoin#93]
./autogen.sh
...
./configure --without-gui --disable-tests
...
make
...
..
.
Making all in src
make[1]: Entering directory '/var/repo/chaincoin/src'
make[2]: Entering directory '/var/repo/chaincoin/src'
make[3]: Entering directory '/var/repo/chaincoin/src/secp256k1'
make[3]: Leaving directory '/var/repo/chaincoin/src/secp256k1'
  CXX      libbitcoin_server_a-alert.o
alert.cpp: In member function ‘bool CAlert::ProcessAlert(const std::vector<unsigned char>&, bool)’:
alert.cpp:232:71: error: no match for call to ‘(boost::signals2::signal<void()>) (const uint256&, ChangeType)’
                 uiInterface.NotifyAlertChanged((*mi).first, CT_DELETED);
                                                                       ^
In file included from /usr/include/boost/signals2/variadic_signal.hpp:42:0,
                 from /usr/include/boost/signals2/signal.hpp:39,
                 from util.h:30,
                 from addrman.h:13,
                 from net.h:10,
                 from alert.cpp:10:
/usr/include/boost/signals2/detail/signal_template.hpp:716:19: note: candidate: boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::operator()(Args ...) [with Combiner = boost::signals2::optional_last_value<void>; Group = int; GroupCompare = std::less<int>; SlotFunction = boost::function<void()>; ExtendedSlotFunction = boost::function<void(const boost::signals2::connection&)>; Mutex = boost::signals2::mutex; R = void; Args = {}; boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type = void]
       result_type operator ()(BOOST_SIGNALS2_SIGNATURE_FULL_ARGS(BOOST_SIGNALS2_NUM_ARGS))
                   ^
/usr/include/boost/signals2/detail/signal_template.hpp:716:19: note:   candidate expects 0 arguments, 2 provided
/usr/include/boost/signals2/detail/signal_template.hpp:720:19: note: candidate: boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::operator()(Args ...) const [with Combiner = boost::signals2::optional_last_value<void>; Group = int; GroupCompare = std::less<int>; SlotFunction = boost::function<void()>; ExtendedSlotFunction = boost::function<void(const boost::signals2::connection&)>; Mutex = boost::signals2::mutex; R = void; Args = {}; boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type = void]
       result_type operator ()(BOOST_SIGNALS2_SIGNATURE_FULL_ARGS(BOOST_SIGNALS2_NUM_ARGS)) const
                   ^
/usr/include/boost/signals2/detail/signal_template.hpp:720:19: note:   candidate expects 0 arguments, 2 provided
alert.cpp:238:71: error: no match for call to ‘(boost::signals2::signal<void()>) (const uint256&, ChangeType)’
                 uiInterface.NotifyAlertChanged((*mi).first, CT_DELETED);
                                                                       ^
In file included from /usr/include/boost/signals2/variadic_signal.hpp:42:0,
                 from /usr/include/boost/signals2/signal.hpp:39,
                 from util.h:30,
                 from addrman.h:13,
                 from net.h:10,
                 from alert.cpp:10:
/usr/include/boost/signals2/detail/signal_template.hpp:716:19: note: candidate: boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::operator()(Args ...) [with Combiner = boost::signals2::optional_last_value<void>; Group = int; GroupCompare = std::less<int>; SlotFunction = boost::function<void()>; ExtendedSlotFunction = boost::function<void(const boost::signals2::connection&)>; Mutex = boost::signals2::mutex; R = void; Args = {}; boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type = void]
       result_type operator ()(BOOST_SIGNALS2_SIGNATURE_FULL_ARGS(BOOST_SIGNALS2_NUM_ARGS))
                   ^
/usr/include/boost/signals2/detail/signal_template.hpp:716:19: note:   candidate expects 0 arguments, 2 provided
/usr/include/boost/signals2/detail/signal_template.hpp:720:19: note: candidate: boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::operator()(Args ...) const [with Combiner = boost::signals2::optional_last_value<void>; Group = int; GroupCompare = std::less<int>; SlotFunction = boost::function<void()>; ExtendedSlotFunction = boost::function<void(const boost::signals2::connection&)>; Mutex = boost::signals2::mutex; R = void; Args = {}; boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type = void]
       result_type operator ()(BOOST_SIGNALS2_SIGNATURE_FULL_ARGS(BOOST_SIGNALS2_NUM_ARGS)) const
                   ^
/usr/include/boost/signals2/detail/signal_template.hpp:720:19: note:   candidate expects 0 arguments, 2 provided
alert.cpp:261:61: error: no match for call to ‘(boost::signals2::signal<void()>) (uint256, ChangeType)’
             uiInterface.NotifyAlertChanged(GetHash(), CT_NEW);
                                                             ^
In file included from /usr/include/boost/signals2/variadic_signal.hpp:42:0,
                 from /usr/include/boost/signals2/signal.hpp:39,
                 from util.h:30,
                 from addrman.h:13,
                 from net.h:10,
                 from alert.cpp:10:
/usr/include/boost/signals2/detail/signal_template.hpp:716:19: note: candidate: boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::operator()(Args ...) [with Combiner = boost::signals2::optional_last_value<void>; Group = int; GroupCompare = std::less<int>; SlotFunction = boost::function<void()>; ExtendedSlotFunction = boost::function<void(const boost::signals2::connection&)>; Mutex = boost::signals2::mutex; R = void; Args = {}; boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type = void]
       result_type operator ()(BOOST_SIGNALS2_SIGNATURE_FULL_ARGS(BOOST_SIGNALS2_NUM_ARGS))
                   ^
/usr/include/boost/signals2/detail/signal_template.hpp:716:19: note:   candidate expects 0 arguments, 2 provided
/usr/include/boost/signals2/detail/signal_template.hpp:720:19: note: candidate: boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::operator()(Args ...) const [with Combiner = boost::signals2::optional_last_value<void>; Group = int; GroupCompare = std::less<int>; SlotFunction = boost::function<void()>; ExtendedSlotFunction = boost::function<void(const boost::signals2::connection&)>; Mutex = boost::signals2::mutex; R = void; Args = {}; boost::signals2::signal<R(Args ...), Combiner, Group, GroupCompare, SlotFunction, ExtendedSlotFunction, Mutex>::result_type = void]
       result_type operator ()(BOOST_SIGNALS2_SIGNATURE_FULL_ARGS(BOOST_SIGNALS2_NUM_ARGS)) const
                   ^
/usr/include/boost/signals2/detail/signal_template.hpp:720:19: note:   candidate expects 0 arguments, 2 provided
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-implicit-fallthrough’
cc1plus: warning: unrecognized command line option ‘-Wno-self-assign’
Makefile:5734: recipe for target 'libbitcoin_server_a-alert.o' failed
make[2]: *** [libbitcoin_server_a-alert.o] Error 1
make[2]: Leaving directory '/var/repo/chaincoin/src'
Makefile:9595: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/var/repo/chaincoin/src'
Makefile:656: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by howardfinter** [comment]
I will fix it.

**Comment by suprnurd** [comment]
@howardfinter Don't worry about it, I pulled in the changes from Hash so you can just clone from the 0.12.X branch now and work directly from there.

This branch will build correctly now.

**Comment by howardfinter** [comment]
Thanks!
